name = "node-dist-worker-poc"
main = "src/worker.ts"
compatibility_date = "2023-08-07"

[vars]
DIRECTORY_LISTING = 'restricted'
CACHE_CONTROL = 'public, max-age=3600, s-maxage=14400'
DIRECTORY_CACHE_CONTROL = 'public, max-age=3600, s-maxage=14400'
COMMONLY_UPDATED_PATHS = [
    '/dist',
    '/dist/',
    '/dist/latest',
    '/dist/latest/',
]

[[r2_buckets]]
binding = "R2_BUCKET"
preview_bucket_name = "node-poc-dev"
bucket_name = "node-poc-prod"
